### ISSUE TITLE
flatpak build fails

### ISSUE THREAD

**Issue by albfan** [waltervargas/gnome-jenkins#1]
we need to add a 

    rm -rf .flatpak-builder

because this error

```
XAB: starting: rofiles-fuse -o /var/lib/jenkins/workspace/gnome-todo-flatpak/.flatpak-builder/rofiles/rofiles-DNHJ6j
Error: module gnome-todo: Error removing file: Directory not empty
XAB: unmounting rofiles-fuse /var/lib/jenkins/workspace/gnome-todo-flatpak/.flatpak-builder/rofiles/rofiles-DNHJ6j
Build step 'Execute shell' marked build as failure
```

I don't even know what it means, but removing that dir looses all cache

**Comment by waltervargas** [comment]
@albfan We need to that as a previous step for the build stage?

**Comment by albfan** [comment]
Yes. I cannot reproduce that on my system. Maybe related with flatpak version. That's why total control of servers is needed

**Comment by albfan** [comment]
that needs ostree installed
